### ISSUE TITLE
loading blast tabulated results

### ISSUE THREAD

**Issue by theBowja** [tripal/tripal_analysis_blast#40]
Hi, I want to ask if this module supports uploading blast tabulated results. The tabulated format has a bunch of [additional attributes](http://www.metagenomics.wiki/tools/blast/blastn-output-format-6) not defined in the XML DTD.

"Generating authentic blast xml output from tabular output is impossible because some of the information, like e.g. the actual alignments, is not present in the latter" [(1)](https://www.biostars.org/p/160476/#160485). Redoing the blast would also take too much time.

If not, then I'm wondering how I might be able to implement this for myself. I'm a little hesitant about working with tables.

Thanks

**Comment by spficklin** [comment]
Hi @theBowja .  Unfortunately there is currently not an importer for the tab delimited output.  At the time that the XML importer was created, it contained more details than the tab delimited output.  We probably could write a tab-delimited importer. The challenge will be that users are free to create any ordering they like to that output and they would have and we'd have to update the visualizer to deal with missing columns.  Which would be a bit of work.  

You could possibly use the Tripal bulk loader (https://tripal.readthedocs.io/en/latest/user_guide/bulk_loader.html). It is meant to import tab-delimited files that don't have a defined structure.  It takes a bit of time to get comfortable with it, but may help if you don't want to redo the blast.

**Comment by bradfordcondon** [comment]
If I’m not mistaken, the rendering of this module requires the xml.  If that’s the case, tab loading wouldn’t be compatible with this module, I think.

**Comment by spficklin** [comment]
Yes @bradfordcondon makes a good point. If you do use the bulk loader you can get details into Chado but there won't be a good way to view it.   So, it may be easiest to just redo the xml.

**Comment by theBowja** [comment]
I had decided use the bulk loading module setting it up according to [this guide](http://gmod.org/wiki/Chado_Best_Practices#Results_from_BLAST). 

It works but there seems to be something wrong with the result. I also don't know if it follows the guide correctly or not. But I'm moving on to do something else so here it is if anyone wants it: [template.txt](https://github.com/tripal/tripal_analysis_blast/files/3340646/template.txt)

First column of tab delimited file should be query_id. Second column should be subject_id.

Here's what the template is supposed to do:
-insert a dbxref for each row for subject_id
--insert 'polypeptide' feature for subject_id
-insert 'match' feature for one hit
-insert 'match_part' feature for one hsp
-insert 'part_of' featurerelationship between the above hsp and hit
-insert analysisfeature record for hsp
-insert featureloc for both query and subject
--feature_id is the previously inserted hsp

**Comment by spficklin** [comment]
Hi @theBowja .  I'm glad you got it working to your liking.  I'm closing this out. But I'm curious, was that your first time using the bulk loader?

**Comment by theBowja** [comment]
Yeah it was my first time using bulk loader. I thought it was pretty straightforward for my purposes after familiarizing with it a bit. Well there weren't really any examples to learn off of. Only thing I don't get was what "mark this field as required" actually does.

Here's an updated template: 
[template draft.txt](https://github.com/tripal/tripal_analysis_blast/files/3363055/template.draft.txt)
I tested it and I believe it has fixed the problem from before. Btw it doesn't handle multiple hits/hsps between the same query and subject.

Changes:
-insert analysisfeature record for both hit and hsp

**Comment by theBowja** [comment]
Does anyone have any advice on how to display the records as tables in the mRNA page or another page?

**Comment by spficklin** [comment]
That's great with the bulk loader.  If you have any suggestions to improve the online docs let us know.  

What records do you want in table format?

**Comment by theBowja** [comment]
Yeah in the [docs](https://tripal.readthedocs.io/en/latest/user_guide/bulk_loader.html) it mentions "Loading templates that have been shared are available on the Tripal website here: http://tripal.info/extensions/bulk-loader-templates." except I don't see anything at that link. I don't know if it's because of my browser or if there's nothing actually there.

For the table, I want to include the db reference from the dbxref record and also the analysisfeature record for hsp. In the future I might also need the analysisfeatureprop records referencing that hsp analysisfeature record but my bulk loader template currently doesn't do anything there.

**Comment by spficklin** [comment]
Oh, yes. That line needs to come out of the online documentation as we no longer have that resource.  It wasn't being used unfortunately.

If the fields you want in a table are already on the page, then it is possible to put them into a vertical table using Drupal's content display settings page for the content type.  Otherwise... if you want them in a horizontal table or if the fields don't already appear on the page then you will have to write PHP code to make it happen.  This is because Tripal provides basic displays for all Chado data and we've done our best to put those together in ways that suit the most common need.  In this case, your arrangement of the data doesn't quite match.  It may be faster to just redo the blast output in XML format, unfortunately. But if you want to try to go down the route of writing your own custom field then I can point you to resources that can help.

**Comment by theBowja** [comment]
If you could point me to some resources, I would very much appreciate it. Thanks.

**Comment by spficklin** [comment]
Okay. The first thing to do is to become familiar (if you are not already) with the Drupal way of programming. It has a bit of a learning curve to get through it.  You can learn about how to create a custom module here: https://www.drupal.org/docs/7/creating-custom-modules.  Or, an online book that walks you through creation of a Drupal 7 module is helpful.  Once you're comfortable with Drupal you can begin to use our Tripal API to integrate your custom module with Tripal. We have online developer documentation here: https://tripal.readthedocs.io/en/latest/dev_guide.html.  Because you are interested in creating a new visulaization for blast results housed in the way you loaded them, you'll be interested in the section on creating a custom field: https://tripal.readthedocs.io/en/latest/dev_guide/custom_field.html.  

That should get you going and you can always ask for help by posting issues on this GitHub repository.
